#!/usr/bin/perl

  # first spit out the C definition

$date=localtime();

$header =
"#ifndef RGB_H
#define RGB_H

// DO NOT EDIT  Generated by rgrb2c.pl on $date

typedef struct rgbSpec {
	int r,g,b;
	const char *name;
} rgb;

struct rgbSpec rgbs[] = { 
";

print $header;

my $lineno=0;
while (<>) {
	next if ($lineno++==0);

  my $n= split();

  	my @a= split();
	print "\t{ $a[0], $a[1], $a[2], \t\"$a[3]";
  	for (my $i=4; $i<$n; $i++) {
		print " $a[$i]";
  	}
   print "\" },\n";
}

print "};\n";
print "\n";
print "#endif\n";

